### ISSUE TITLE
Backend server sometimes does not wait for database to fully initialize

### ISSUE THREAD

**Issue by Erik-McKelvey** [SENG-499-Company2-B01/Backend#24]
I'm running into an issue where the backend server container starts up before the database, so then the server fails to connect to the database and shuts down, then afterwards the database starts normally

I've had this issue before in another project I'll paste the code I used to solve it except the difference is it used a mysql database so changes may be needed

in mongo_db:
```
depends_on:
      # Ensure db is fully running before initializing backend
      db:
        condition: service_healthy 
```
in backend_server:
```
healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--protocol=TCP"]
      interval: 3s
      timeout: 5s
      retries: 10 
```
